// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Vendas.Models
{
    [Table("tb_Cliente")]
    public partial class TbCliente
    {
        public TbCliente()
        {
            TbVenda = new HashSet<TbVenda>();
        }

        [Key]
        [Column("Id_Cliente")]
        public int IdCliente { get; set; }
        [Required]
        [Column("Nome_Cliente")]
        [StringLength(50)]
        public string NomeCliente { get; set; }
        [Column("Telefone_Cliente")]
        [StringLength(15)]
        public string TelefoneCliente { get; set; }
        [Column("Data_Nascimento", TypeName = "date")]
        public DateTime? DataNascimento { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<TbVenda> TbVenda { get; set; }
    }
}