// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Vendas.Models
{
    [Table("tb_Produto")]
    public partial class TbProduto
    {
        public TbProduto()
        {
            TbVenda = new HashSet<TbVenda>();
        }

        [Key]
        [Column("Id_Produto")]
        public int IdProduto { get; set; }
        [Required]
        [Column("Nome_Produto")]
        [StringLength(50)]
        public string NomeProduto { get; set; }
        [Column("Descricao_Produto")]
        [StringLength(100)]
        public string DescricaoProduto { get; set; }
        [Required]
        [Column("Unidade_Produto")]
        [StringLength(5)]
        public string UnidadeProduto { get; set; }
        [Column("Preco_Compra_Produto", TypeName = "decimal(18, 0)")]
        public decimal PrecoCompraProduto { get; set; }
        [Column("Preco_Venda_Produto", TypeName = "decimal(18, 0)")]
        public decimal PrecoVendaProduto { get; set; }
        [Column("Estoque_Produto")]
        public int EstoqueProduto { get; set; }
        [Column("Imagem_Produto", TypeName = "image")]
        public byte[] ImagemProduto { get; set; }

        [InverseProperty("IdProdutoNavigation")]
        public virtual ICollection<TbVenda> TbVenda { get; set; }
    }
}